### ISSUE TITLE
Request - 1v1

### ISSUE THREAD

**Issue by lazhoroni** [Franc1sco/Give-ExoJumps#2]
Do you code Exo Jump Boots round for multi 1v1? Other equipment to be awarded when round starts: Bump Mines, Riffle Preference, Pistol Preference, Knife.
Do you code Tactical Shield round for multi 1v1? Other equipment to be awarded when round starts: Pistol Preference.

**Comment by Franc1sco** [comment]
I could. We talk on discord or telegram better.

-Telegram -> https://t.me/Franc1sco 
-Discord -> Franc1sco#7876
